markdown: GFM
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
title: TimerCue Privacy Policy & Terms of Use
description: Privacy Policy and Terms of Use for TimerCue App
